// <auto-generated />
using System;
using HomeFinder.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeFinder.Migrations
{
    [DbContext(typeof(HomeFinderContext))]
    partial class HomeFinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeFinder.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("apartment_number");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("district");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("longitude");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("region");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("street_address");

                    b.HasKey("AddressId")
                        .HasName("PK__Address__CAA247C819578DA4");

                    b.HasIndex("ApartmentId");

                    b.HasIndex(new[] { "AddressId" }, "UQ__Address__CAA247C9A9CDB487")
                        .IsUnique();

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.Administrator", b =>
                {
                    b.Property<int>("AdministratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("administrator_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministratorId"));

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("AdministratorId")
                        .HasName("PK__Administ__3871E7AC10D86DA4");

                    b.HasIndex(new[] { "AdministratorId" }, "UQ__Administ__3871E7AD412B365C")
                        .IsUnique();

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.Property<int?>("Rooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("rooms");

                    b.Property<int?>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("size");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ApartmentId")
                        .HasName("PK__Apartmen__DC51C2EC9A8FCAC2");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ApartmentId" }, "UQ__Apartmen__DC51C2ED744BE6EB")
                        .IsUnique();

                    b.ToTable("Apartment", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.ApartmentViewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentViewLog", "dbo");
                });

            modelBuilder.Entity("HomeFinder.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("date_time");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__A50828FC348EAF35");

                    b.HasIndex("AddressId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__Appointm__A50828FDA0265C85")
                        .IsUnique();

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__46ACF4CB41B10C30");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "FavoriteId" }, "UQ__Favorite__46ACF4CAD1661F53")
                        .IsUnique();

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.LandlordSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("current_period_end_utc");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasFilter("[stripe_subscription_id] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LandlordSubscriptions", "dbo");
                });

            modelBuilder.Entity("HomeFinder.Models.Payment", b =>
                {
                    b.Property<long>("ClickTransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("click_trans_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClickTransId"));

                    b.Property<int?>("Action")
                        .HasColumnType("int")
                        .HasColumnName("action");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<long?>("ClickPaydocId")
                        .HasColumnType("bigint")
                        .HasColumnName("click_paydoc_id");

                    b.Property<int?>("Error")
                        .HasColumnType("int")
                        .HasColumnName("error");

                    b.Property<string>("ErrorNote")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("error_note");

                    b.Property<string>("MerchantTransId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("merchant_trans_id");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("SignString")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sign_string");

                    b.Property<string>("SignTime")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sign_time");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ClickTransId")
                        .HasName("PK__Payment__80EB26ED9E92DFD1");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClickTransId" }, "UQ__Payment__80EB26ECF00931D4")
                        .IsUnique();

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_path");

                    b.HasKey("PhotoId")
                        .HasName("PK__Photo__CB48C83D17D6F1B1");

                    b.HasIndex("ApartmentId");

                    b.HasIndex(new[] { "PhotoId" }, "UQ__Photo__CB48C83CEA866E3D")
                        .IsUnique();

                    b.ToTable("Photo", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.ReviewApartment", b =>
                {
                    b.Property<int>("RApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("r_apartment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RApartmentId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RApartmentId")
                        .HasName("PK__Review A__4F55CBAA3BAE45B3");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "RApartmentId" }, "UQ__Review A__4F55CBABF9255E8D")
                        .IsUnique();

                    b.ToTable("Review Apartment", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsLandlord")
                        .HasColumnType("bit")
                        .HasColumnName("isLandlord");

                    b.Property<bool?>("IsTenant")
                        .HasColumnType("bit")
                        .HasColumnName("isTenant");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("passport_series")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Pinfl")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("pinfl");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370F33A45A75");

                    b.HasIndex(new[] { "UserId" }, "UQ__User__B9BE370E4B593BC0")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.UserLoginLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("login_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("PK__User log__9E2397E0C76C83BC");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "LogId" }, "UQ__User log__9E2397E1D39DF833")
                        .IsUnique();

                    b.ToTable("User login log", (string)null);
                });

            modelBuilder.Entity("HomeFinder.Models.Address", b =>
                {
                    b.HasOne("HomeFinder.Models.Apartment", "Apartment")
                        .WithMany("Addresses")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Address__apartme__6C190EBB");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("HomeFinder.Models.Apartment", b =>
                {
                    b.HasOne("HomeFinder.Models.User", "User")
                        .WithMany("Apartments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Apartment__user___656C112C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeFinder.Models.ApartmentViewLog", b =>
                {
                    b.HasOne("HomeFinder.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("HomeFinder.Models.Appointment", b =>
                {
                    b.HasOne("HomeFinder.Models.Address", "Address")
                        .WithMany("Appointments")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Appointme__addre__70DDC3D8");

                    b.HasOne("HomeFinder.Models.Apartment", "Apartment")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK__Appointme__apart__6FE99F9F");

                    b.Navigation("Address");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("HomeFinder.Models.Favorite", b =>
                {
                    b.HasOne("HomeFinder.Models.Apartment", "Apartment")
                        .WithMany("Favorites")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Favorite__apartm__797309D9");

                    b.HasOne("HomeFinder.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Favorite__user_i__787EE5A0");

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeFinder.Models.Payment", b =>
                {
                    b.HasOne("HomeFinder.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Payment__user_id__7D439ABD");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeFinder.Models.Photo", b =>
                {
                    b.HasOne("HomeFinder.Models.Apartment", "Apartment")
                        .WithMany("Photos")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Photo__apartment__74AE54BC");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("HomeFinder.Models.ReviewApartment", b =>
                {
                    b.HasOne("HomeFinder.Models.Apartment", "Apartment")
                        .WithMany("ReviewApartments")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Review Ap__apart__07C12930");

                    b.HasOne("HomeFinder.Models.User", "User")
                        .WithMany("ReviewApartments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Review Ap__user___06CD04F7");

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeFinder.Models.UserLoginLog", b =>
                {
                    b.HasOne("HomeFinder.Models.User", "User")
                        .WithMany("UserLoginLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__User logi__user___02084FDA");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeFinder.Models.Address", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HomeFinder.Models.Apartment", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Photos");

                    b.Navigation("ReviewApartments");
                });

            modelBuilder.Entity("HomeFinder.Models.User", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Favorites");

                    b.Navigation("Payments");

                    b.Navigation("ReviewApartments");

                    b.Navigation("UserLoginLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
